### ISSUE TITLE
one issue

### ISSUE THREAD

**Issue by kenshouatare** [takanotume24/paper-transration-helper#2]
文章の冒頭がNot で始まる時に、No.となるようです。"Not coincidentally,"→"No.coincidentally,."の如くです。

**Comment by takanotume24** [comment]
ご報告ありがとうございます｡正規表現での``.`` をエスケープし忘れているのが原因でした｡また他に何かあればよろしくお願いします｡

**Comment by kenshouatare** [comment]
早速のご対応ありがとうございます。報告した甲斐がありました。本来はじめに申し上げるべきでしたが、大変有用なツールを作成いただき、ありがとうございます。今後さらに使用してみて、何かあればまたご報告いたします。

**Comment by takanotume24** [comment]
いえいえ､こちらこそ使っていただきありがとうございますm(_ _)m そう言っていただけるととても励みになります(^^)   今後も機能追加､バグ修正などどうぞお気軽にご報告ください｡
